[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-world"
version = "0.1.0"
description = "A simple PySide6 hello world example."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "PySide6>=6.2",
]
